### ISSUE TITLE
iOS deprecation warnings

### ISSUE THREAD

**Issue by peacechen** [oojr/react-native-battery#11]
Building with React Native 0.54.4 on iOS results in deprecation warnings:

> /..../node_modules/react-native-battery/ios/RCTBattery/BatteryManager.m:82:34: warning: 'sendDeviceEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead [-Wdeprecated-declarations]
>     [self.bridge.eventDispatcher sendDeviceEventWithName:@"BatteryStatus" body:batteryData];
>                                  ^
> In file included from /..../node_modules/react-native-battery/ios/RCTBattery/BatteryManager.m:10:
> /..../ios/Pods/Headers/Public/React/React/RCTEventDispatcher.h:84:1: note: 'sendDeviceEventWithName:body:' has been explicitly marked deprecated here
> __deprecated_msg("Subclass RCTEventEmitter instead");
> ^
> In module 'Darwin' imported from /..../ios/Pods/Headers/Public/React/React/RCTUtils.h:10:
> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/usr/include/sys/cdefs.h:180:48: note: expanded from macro '__deprecated_msg'
>         #define __deprecated_msg(_msg) __attribute__((deprecated(_msg)))
>                                                       ^
> 1 warning generated.
>

**Comment by peacechen** [comment]
These warnings also pop up

> [warn][tid:main][RCTModuleData.mm:67] Module BatteryManager requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

**Comment by oojr** [comment]
@peacechen will upgrade soon and try to keep the same api

**Comment by oojr** [comment]
deprecations warnings removed
