### ISSUE TITLE
onBatteryStatus method is not calling when there is a battery status change

### ISSUE THREAD

**Issue by LavanyaJoga** [oojr/react-native-battery#17]
Do this plugin  runs continuously and gets battery information when ever there is battery percentage change.

**Comment by oojr** [comment]
No, you have to use a timer like setInterval along with it to achieve that functionality https://facebook.github.io/react-native/docs/timers

**Comment by zoobibackups** [comment]
onBatteryStatus is only working on android not on iOS, why the issue is closed without resolving?
