### ISSUE TITLE
Follow safeExtGet to allow configure min/target/compile sdk version and build tool version

### ISSUE THREAD

**Issue by CAMOBAP** [oojr/react-native-battery#18]
In many different repositories, I saw the approach which allows configuring: 
 - `compileSdkVersion`
 - `buildToolsVersion`
 - `minSdkVersion`
 - `targetSdkVersion`

It looks like this:
```
def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion safeExtGet('compileSdkVersion', 26)
    buildToolsVersion safeExtGet('buildToolsVersion', '26.0.3')

    defaultConfig {
        minSdkVersion safeExtGet('minSdkVersion', 16)
        targetSdkVersion safeExtGet('targetSdkVersion', 26)
        versionCode 1
        versionName "1.0"
    }
   ...
}

...
```

Example is taken from https://github.com/itinance/react-native-fs/blob/master/android/build.gradle#L18-L23

I can provide PR if need

**Comment by oojr** [comment]
@CAMOBAP795 sure submit a pr

**Comment by CAMOBAP** [comment]
@oojr could you please review PR https://github.com/oojr/react-native-battery/pull/19

**Comment by CAMOBAP** [comment]
@oojr thanks, I hope you will have a chance to release it soon

**Comment by oojr** [comment]
@CAMOBAP795 I published it thanks, I didn't notice the example link at first, I like the project react-native-fs
