### ISSUE TITLE
Compilation Fails

### ISSUE THREAD

**Issue by edencakir** [oojr/react-native-battery#2]
After linking manually as described, running react-native run-ios fails.

`/node_modules/react-native-battery/ios/RCTBattery/BatteryManager.m:8:9: fatal error: 
      'RCTBridge.h' file not found
#import "RCTBridge.h"
        ^
1 error generated.
`

**Comment by oojr** [comment]
sorry I need to update the readme can you try again with react-native link

**Comment by vpontis** [comment]
Hmm, yea is the README still wrong? 

I am having trouble finding the file specified here: http://url.brentvatne.ca/1gqUD

**Comment by oojr** [comment]
updated readme... `react-native link`
