### ISSUE TITLE
No Android Support?

### ISSUE THREAD

**Issue by natterstefan** [oojr/react-native-battery#4]
Hello @oojr,

I am somehow sure I know the answer already, but I ask anyways: is this project also for Android? Because I have an Android-only project and `react-native link` does not do something. Also I am not able to use `BatteryManager` (like in the Readme) afterwards.

Thanks for your help.

**Comment by oojr** [comment]
hey @natterstefan here is an android battery manager https://github.com/robinpowered/react-native-device-battery I will try to bring android support to this when I can afford a better test device

**Comment by natterstefan** [comment]
@oojr alright, thanks for the quick response. I will take a look at it.
