### ISSUE TITLE
isPlugged returns false if the device is plugged into power and the battery is 100% charged.

### ISSUE THREAD

**Issue by lihue** [oojr/react-native-battery#7]
If an iOS device is plugged into power and the battery is 100% charged, isPlugged returns false instead of true.

According to the Apple documentation, you should also check for battery state UIDeviceBatteryStateFull (The device is plugged into power and the battery is 100% charged.)

See https://developer.apple.com/documentation/uikit/uidevicebatterystate/uidevicebatterystatefull

**Comment by jdegger** [comment]
Is this scheduled to be fixed?

**Comment by oojr** [comment]
@jdegger I didn't even see this until now, mentions give me emails

**Comment by jdegger** [comment]
@oojr it might be a good idea to turn on all notifications for your own repos :)

We are still facing this bug, would be great if it could be fixed! Let me know if we can be of any assistance.
