### ISSUE TITLE
Adding Android support

### ISSUE THREAD

**Issue by peacechen** [oojr/react-native-battery#8]
I'm working on adding Android support, basing the code on this SO example:
https://stackoverflow.com/questions/44920299/react-native-get-battery-status-level

Would @oojr be up for merging a PR after it's been tested?

**Comment by oojr** [comment]
@peacechen yes I can merge a pr

**Comment by peacechen** [comment]
@oojr PR #9 is ready and tested

**Comment by oojr** [comment]
@peacechen published
